tiff(file="88_final.tiff",res=150,width=10000,height=12000)
par(mfrow=c(10,1))
par(mar=c(0.5,5,1,0.5))
pop<-read.table("arranged_name.list",as.is=T)
ord<-order(pop[,1])
q<-read.table("88_ind_final.2_0.Q")
barplot(t(q)[,ord],col=rainbow(3),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.3_0.Q")
barplot(t(q)[,ord],col=rainbow(4),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.4_0.Q")
barplot(t(q)[,ord],col=rainbow(5),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.5_0.Q")
barplot(t(q)[,ord],col=rainbow(6),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.6_0.Q")
barplot(t(q)[,ord],col=rainbow(7),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.7_0.Q")
barplot(t(q)[,ord],col=rainbow(8),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.8_0.Q")
barplot(t(q)[,ord],col=rainbow(9),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(0.5,5,0.5,0.5))
q<-read.table("88_ind_final.9_0.Q")
barplot(t(q)[,ord],col=rainbow(10),space=0,border=NA,xlab="",ylab="",las=2,yaxt='n')
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)

par(mar=c(10,5,0.5,0.5))
q<-read.table("88_ind_final.10_0.Q")
barplot(t(q)[,ord],col=rainbow(11),space=0,border=NA,names.arg= c("ANC_A_GGSI", "ANC_A_GGSI", "ANC_B_RJFC", "ANC_B_RJFC", "ANC_B_RJFC", "ANC_C_GGMI", "ANC_C_GGMI", "ANC_C_GGMI", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_D_TBNC", "ANC_E_PUNB", "ANC_E_PUNB", "ANC_E_PUNB", "ANC_E_PUNB", "ANC_F_IAFC", "ANC_F_IAFC", "ANC_F_IAFC", "ANC_F_IAFC", "ANC_G_NICO", "ANC_G_NICO", "ANC_G_NICO", "ANC_G_NICO", "ANC_H_ANKL", "ANC_H_ANKL", "ANC_H_ANKL", "ANC_H_ANKL", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_KADK", "BBC_A_NONB", "BBC_B_AYCM", "BBC_C_LCMY", "BBC_C_LCMY", "BBC_C_LCMY", "BBC_C_LCMY", "BBC_D_LCJY", "BBC_E_LCMC", "BBC_F_SILK", "BBC_F_TBBC", "BBC_F_TBBC", "BBC_F_TBBC", "BBC_G_LCEM", "BBC_G_LCEM", "BBC_G_LCEM", "BBC_H_XBBC", "BBC_H_XBBC", "BBC_H_XBBC", "BBC_H_XBBC", "BBC_H_XBBC", "BBC_I_YOSK", "BBC_I_YOSK", "BBC_I_YOSK", "BBC_I_YOSK", "BBC_J_LCTF", "Com_D_OTCC", "Com_D_OTCC", "Com_D_OTCC", "Com_D_OTCC", "Com_D_OTCC"), xlab="",ylab="",las=2,yaxt='n',cex.names=3)
axis(2,at=c(0.0,0.2,0.4,0.6,0.8,1.0), lwd = 4,tck = -0.01,cex.axis=2,font = 5,las=2,line=-18)
dev.off()
